### ISSUE TITLE
High-level Architecture Diagram

### ISSUE THREAD

**Issue by xkbt777** [MITS-Felucca/Felucca#11]

**Comment by xkbt777** [comment]
I came up with basic architecture design, including several managers and drew a module and architecture design graph of it.

**Comment by Orankarl** [comment]
Add several sequence diagrams to show the interaction between users, Felucca and Pharos tools.

**Comment by Orankarl** [comment]
Update sequence diagrams.

**Comment by xkbt777** [comment]
Redraw a new version detailed diagram for modules in architecture and layers inside.

**Comment by xkbt777** [comment]
Draw a new diagram using lucichart.
