### ISSUE TITLE
Template for architecture diagram

### ISSUE THREAD

**Issue by xkbt777** [MITS-Felucca/Felucca#15]

**Comment by hyasar** [comment]
[Architecture Report_v1.0.pdf](https://github.com/MITS-Felucca/Felucca/files/4434406/Architecture.Report_v1.0.pdf)
![architecture_1stDraft](https://user-images.githubusercontent.com/2229818/78505295-9b93fa00-7740-11ea-8153-c2d636645bb1.png)
![context_diagram](https://user-images.githubusercontent.com/2229818/78505299-9e8eea80-7740-11ea-90db-225479434595.png)
<img width="1027" alt="Activity Diagram" src="https://user-images.githubusercontent.com/2229818/78505302-a51d6200-7740-11ea-991d-d2425d6b7d84.png">
<img width="535" alt="Baselines" src="https://user-images.githubusercontent.com/2229818/78505303-a8185280-7740-11ea-8a5e-ae1961a0b1cb.png">
![New - CASWebService - Module Decompose View](https://user-images.githubusercontent.com/2229818/78505305-ab134300-7740-11ea-84f8-e328338e3c50.png)
![New - CASWebService - Module Uses View](https://user-images.githubusercontent.com/2229818/78505308-ad759d00-7740-11ea-83bd-acb768382289.png)
![New - Context Diagram](https://user-images.githubusercontent.com/2229818/78505311-b1092400-7740-11ea-843f-119197a0658d.png)
![New - Layer 2 - Dynamic Connection Service C C](https://user-images.githubusercontent.com/2229818/78505313-b36b7e00-7740-11ea-96f0-75e973308455.png)
![New - Parser - Module Decompose View](https://user-images.githubusercontent.com/2229818/78505315-b6ff0500-7740-11ea-938e-88c24268bac4.png)
![New - sequence - connect](https://user-images.githubusercontent.com/2229818/78505317-b9615f00-7740-11ea-9ab6-6ccb48914fc5.png)
![New - sequence - Parse Report](https://user-images.githubusercontent.com/2229818/78505321-bcf4e600-7740-11ea-8c50-d28c8e4a9f31.png)
![New - sequence - register](https://user-images.githubusercontent.com/2229818/78505324-c1b99a00-7740-11ea-9750-4c966871824f.png)
![New - sequence - select controllers](https://user-images.githubusercontent.com/2229818/78505327-c4b48a80-7740-11ea-8a9c-1e51ebbe1bbc.png)
![New - Top Level - Dynamic View](https://user-images.githubusercontent.com/2229818/78505329-c716e480-7740-11ea-894f-f8a493c68a7b.png)
![New - Top Level - Module View](https://user-images.githubusercontent.com/2229818/78505330-ca11d500-7740-11ea-8f16-9ebaaaca9f92.png)
![Physical View](https://user-images.githubusercontent.com/2229818/78505332-cc742f00-7740-11ea-88ff-8f8706400866.png)
