### ISSUE TITLE
Presentation template

### ISSUE THREAD

**Issue by xkbt777** [MITS-Felucca/Felucca#18]

**Comment by hyasar** [comment]
Here are  samples from previous years

**Comment by hyasar** [comment]
[EOSP.pptx](https://github.com/MITS-Felucca/Felucca/files/4499820/EOSP.pptx)
[EOSP_slides_final.pptx](https://github.com/MITS-Felucca/Felucca/files/4499821/EOSP_slides_final.pptx)
[HM Med Device Spring EoSP.pptx](https://github.com/MITS-Felucca/Felucca/files/4499822/HM.Med.Device.Spring.EoSP.pptx)
[PIN_EOSP.pptx](https://github.com/MITS-Felucca/Felucca/files/4499830/PIN_EOSP.pptx)

**Comment by hyasar** [comment]
[Team NFSW - Spring EOSP.pptx](https://github.com/MITS-Felucca/Felucca/files/4499831/Team.NFSW.-.Spring.EOSP.pptx)
[EOSP-Radioactives2019Spring.pptx](https://github.com/MITS-Felucca/Felucca/files/4499832/EOSP-Radioactives2019Spring.pptx)
[Team Rainbow EOSP Slides.pptx](https://github.com/MITS-Felucca/Felucca/files/4499833/Team.Rainbow.EOSP.Slides.pptx)
[SweetDreams_EOSP.pptx](https://github.com/MITS-Felucca/Felucca/files/4499834/SweetDreams_EOSP.pptx)
